export const FETCH_USER = 'FETCH_USER';
export const FETCH_RECIPIES = 'FETCH_RECIPIES';
export const CHANGE_DAY = 'CHANGE_DAY';
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_SAVED_RECIPIES = 'FETCH_SAVED_RECIPIES';
